# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242efeb8572d17727a8ca31c5113a59a92fa15cf1804e1a16c07596fa387d4bc57a9991769724445950e7fe8681913f051edaae4c0a89df9be1aeab8697e9306

test:
  secret_key_base: d769c8a1057ef048ef3e6797ac041015ac895e21a0020c5b64f2fe7885dbf02bdcd9251b7b2544e0d1f7c33c74df466236dfc3afb843d39956ebf89ef093156c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
